Add documentation for the wpseo_enable_tracking filter
Yoast/developer-docs pull request #129
Opened 2021-05-05 10:25 UTC by JustinyAhin

## Summary
Add documentation for the wpseo_enable_tracking filter

## Quality assurance

* [ ] I have altered a filename
    * [ ] I have adjusted the ID and editUrl properties accordingly and updated all internal links. 
      The following redirects need to be created:
        * 
    * [x] I have adjusted the sidebar entry in the [developer-site](https://github.com/Yoast/developer-site) repository
* [x] I have tested my changes

2021-05-12 07:45 UTC, d-claassen requested changes

2021-05-12 07:45 UTC, d-claassen commented on docs/customization/yoast-seo/filters/wpseo-data-tracking-filter.md
> +Yoast SEO has a usage tracking feature to track basic site data, server date, the plugin usage and the others plugins on the site as well as the theme used on the site.
Just checking: is it the **date** of the server, or **data** about the server? If date, we might want to rephrase that part to prevent confusion.

Also, `others plugins` should be `other plugins`.

2021-05-12 07:45 UTC, d-claassen commented on docs/customization/yoast-seo/filters/wpseo-data-tracking-filter.md
> +sidebar_label: Enables the data tracking of Yoast SEO Premium and add-ons
The description sounds like this can also be used to enable tracking for Yoast SEO free, so not specifically Premium and add-ons

2021-05-12 07:45 UTC, d-claassen commented on docs/customization/yoast-seo/filters/wpseo-data-tracking-filter.md
> +The `wpseo_enable_tracking` filter allows you to alter if whether Yoast SEO will track this data.
Pick one: `if` or `whether`. I'm not sure what we're doing in other parts of the documentation. Maybe we can follow some other pages and be consistent overall. Otherwise I'd go for `whether`.

2021-05-19 09:04 UTC, JustinyAhin commented on docs/customization/yoast-seo/filters/wpseo-data-tracking-filter.md
> +Yoast SEO has a usage tracking feature to track basic site data, server date, the plugin usage and the others plugins on the site as well as the theme used on the site.
It is the server data.

2021-06-08 07:30 UTC, d-claassen approved these changes

2021-06-08 07:31 UTC, merged