created windows setup document
Yoast/developer-docs pull request #95
Opened 2020-09-29 08:34 UTC by increddibelly

rough first version of the windows development setup doc

2020-09-29 08:35 UTC, increddibelly commented
@omarreiss @moorscode @Djennez @jdevalk first version, this probably needs a bit of polishing. I'm going to start with adding the screenshots I've made.

2020-10-08 07:53 UTC, jcomack requested changes
CR done 🚧 

This PR feels like a hybrid between https://github.com/Yoast/developer-docs/blob/master/docs/development/environment/tools.md and https://github.com/Yoast/developer-docs/blob/master/docs/development/environment/setup.md and a large portion of the doc, differs in both flow and form. I've added a suggestion on the last section of the doc on how we can ensure that we don't end up with duplicate content.

I'd also suggest you look at some of the other docs to gain a better understanding of the flow and form of the docs, so we can ensure a certain standard of consistency across all docs.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +## Set up a few helper applications:
This header seems unnecessary. I'd suggest removing it, as a lot of the suggestions following it, are about more than just helper applications (i.e. Git, PHP etc are not helper applications).

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +###### Git ######
Please use the standard Markdown syntax of only using hashbangs _before_ the header (i.e. `### Git` and not `### Git ###`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[NotePad++](https://notepad-plus-plus.org/downloads/) a developer's swiss army knife.
Not sure why this should fall under the Git section?

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +###### Git ######
Seems like this header is a duplicate and nested too deeply.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[GitExtensions](https://github.com/gitextensions/gitextensions/releases/) is a powerful Git gui which you'll need to access our Git Repositories from a Windows machine
Please capitalize `gui` to `GUI`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +After installation, GitExtensions will alert you of any missing configurations and you'll need to configure any missing fields. One of the first steps would be to download [Git](https://git-scm.com/d
It seems to me that installing Git should be the very first thing you do in this list of steps, prior to installing a GUI.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +![GitExtensions setup](./screenshots/win_gitextensions_setup_global_config.png)
Images should be places in the `/docs/static/img` directory and linked to as follows, if you want the image to show:

```js
<img src={useBaseUrl( 'img/win_gitextensions_setup_global_config.png' )} alt='GitExtensions setup' />
```

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +![GitExtensions setup](./screenshots/win_gitextensions_setup_unix_tools.png)
Images should be places in the `/docs/static/img` directory and linked to as follows, if you want the image to show:

```js
<img src={useBaseUrl( 'img/win_gitextensions_setup_unix_tools.png' )} alt='GitExtensions setup' />
```

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +Please make sure to set the line endings to **Commit Unix-style line endings**, as you'll be working with teammates whose environment is not compatible with Windows CRLF newlines.
This an exact copy of line 38. Please remove.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +### PHP ###
Please refer to my previous comment regarding the style of headers and fix this section accordingly.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +Carefully follow the steps on the [XDebug installation page](https://xdebug.org/docs/install) in the `Installing on Windows` section.
Header levels are off (i.e. too deep).

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +##### Php #####
This seems like a duplicate header and doesn't make much sense, in that regard. Additionally, I feel that, just like with Git, installing PHP should come before installing an IDE and thus this section should be moved up.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[VScode](https://code.visualstudio.com/download) is a very nice cross platform IDE with support for all sorts of languages, including PHP and typescript / javscript that we use.
`cross platform` should be `cross-platform`, `typescript` should be `TypeScript`, `javscript` should be `JavaScript`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[PhpStorm](https://www.jetbrains.com/phpstorm/download/#section=windows) is a great IDE for php and related code.
`php` should be `PHP`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +Please follow [Jeff Geerling's  excellent guide on installing and configuring PHP on windows](https://www.jeffgeerling.com/blog/2018/installing-php-7-and-composer-on-windows-10) that I wouldn't dare
`[...] that I wouldn't dare improve` makes it feel like this doc page is more of a blog post and doesn't fit the overall writing-style used across the developer portal. Please remove this.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +Make sure you add your php folder to your path environment variable (Press Start > type 'edit environment variables' > click the **Path** line, click edit > New > Browse > navigate to the folder that
`php` should be `PHP`. I'd also suggest wrapping `*php.exe*` with backticks instead of asterisks.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +Download and install [Composer for windows](https://getcomposer.org/download/) which performs some project wide tasks.
`windows` should be `Windows`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +### Javascript ###
Please refer to my previous comment regarding the style of headers and fix this section accordingly.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[nvm-windows](https://github.com/coreybutler/nvm-windows/releases) is not quite the NVM Node Version Manager for windows, but it's doing an excellent impersonation.
Header levels are off (i.e. too deep).

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[Chocolatey](https://chocolatey.org/docs/installation) is a javascript package manager
`javascript` should be `JavaScript`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[nvm-windows](https://github.com/coreybutler/nvm-windows/releases) is not quite the NVM Node Version Manager for windows, but it's doing an excellent impersonation.
`windows` should be `Windows`. Additionally, the line `[...] but it's doing an excellent impersonation` feels out of place here, as it's an opinion, which would be better suited for a blog post.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +- grunt > do the fixes
Header levels are off (i.e. too deep).

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +### Platform ###
Please refer to my previous comment regarding the style of headers and fix this section accordingly.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[Docker](https://docs.docker.com/docker-for-windows/install/) download and install. Read carefully, follow the steps, you may need to tweak or install some additional items.
I'd suggest editing `Read carefully, follow the steps, you may need to tweak or install some additional items.` to `Read carefully and follow the steps. You may need to tweak or install some additional items, depending on your setup.`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[MySql Workbench](https://dev.mysql.com/downloads/workbench/) is an easy way to access the wordpress databases. Registration is not required, just click `Download` > `No thanks, just start my downloa
`MySql` should be `MySQL` and `wordpress` should be `WordPress`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +![Git Bash shortcut](./screenshots/win_git_bash_startmenu.png)
Images should be places in the `/docs/static/img` directory and linked to as follows, if you want the image to show:

```js
<img src={useBaseUrl( 'img/win_git_bash_startmenu.png' )} alt='Git Bash shortcut' />
```

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +###### and finally... ######
This header doesn't seem to have much added value. I'd suggest removing it.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +open a terminal or powershell window, run
`open` should be capitalized and `powershell` should be `PowerShell`. Additionally, because you're starting a list of commands to run, `run` should be followed by a `:`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +- `choco install gsudo`. This will download and install a sudo command line option that enables shell scripts to ask for elevation on windows.
`windows` should be `Windows`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +- `choco install yarn`. Yarn ties our javascript code together.
Yarn is a package manager that gets very little mention in this article and might be confusing. Additionally, `Yarn ties our javascript code together` doesn't mean much to the uninitiated and thus should be replaced with a better description. Lastly, `javascript` should be `JavaScript`.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +- `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`. This allows scrips such as grunt to run.
`scrips` should be `scripts` and `grunt` should be wrapped in backticks.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +- grunt > do the fixes
This seems incomplete. The commands need to be wrapped in backticks and the descriptions aren't finished.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +After you've cloned the repositories, you can navigate to `basic.wordpress.test` in your browser to see the development environment. Open the plugin directory in your IDE and you should be ready to d
This entire section seems to be a direct copy of https://github.com/Yoast/developer-docs/blob/master/docs/development/environment/setup.md, only with slight alterations here and there for Windows users. In essence, we're introducing duplicate content which might not only impact our SEO, but will also mean we need to maintain the same story twice.

My suggestion would be to alter the _original_ doc to show both what steps to take on OSX and on Windows when it comes to setting up PhpStorm etc.

2020-10-08 07:53 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +- `choco install gsudo`. This will download and install a sudo command line option that enables shell scripts to ask for elevation on windows.
Please use the `* List Item` style for lists such as these.

2020-11-27 10:16 UTC, increddibelly commented on docs/development/environment/setup-windows.md
> +[NotePad++](https://notepad-plus-plus.org/downloads/) a developer's swiss army knife.
the installation of git on windows asks for a default text editor. you might as well setup the correct one in one go. The order is OK, the structure is weird indeed.

2020-11-27 12:48 UTC, jcomack requested changes
CR2 done 🚧

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +Please make sure to set the line endings to **Commit Unix-style line endings**, as you'll be working with teammates whose environment is not compatible with Windows CRLF newlines.
This block is a duplicate of a part of line 24.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup.md
> +This page describes the process of how we set up development environments at Yoast on a mac / linux machine.
`mac / linux` needs to be be capitalized.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +![Git Bash shortcut](./screenshots/win_git_bash_startmenu.png)
This feedback doesn't seem to have been processed.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[MySql Workbench](https://dev.mysql.com/downloads/workbench/) is an easy way to access the wordpress databases. Registration is not required, just click `Download` > `No thanks, just start my downloa
This feedback doesn't seem to have been processed.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +### Git
Please add an empty line above each of these headers to ensure consistency.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +### Git / GitHub
Git seems to be 'duplicated' as a section on line 20. Consider consolidating them into one section instead.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +### MySql Workbench
`MySql` should be `MySQL`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +To manage and search your database in an easy and quick way, use [Mysql Workbench](https://dev.mysql.com/downloads/workbench/).
`MySql` should be `MySQL`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +Make sure you add your php folder to your path environment variable (Press Start > type 'edit environment variables' > click the **Path** line, click edit > New > Browse > navigate to the folder that
`php` should be `PHP`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +[VScode](https://code.visualstudio.com/download) is a very nice cross platform IDE with support for all sorts of languages, including PHP and typescript / javscript that we use.
`typescript` should be `TypeScript` and `javscript` should be `JavaScript`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +[PhpStorm](https://www.jetbrains.com/phpstorm/download/#section=windows) is a great IDE for php and related code.
`php` should be `PHP`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +Download and install [Composer for windows](https://getcomposer.org/download/) which allows you to perform project tasks.
`windows` should be `Windows`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +[Chocolatey](https://chocolatey.org/docs/installation) is a javascript package manager
`javascript` should be `JavaScript`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +[nvm-windows](https://github.com/coreybutler/nvm-windows/releases) is not quite the NVM Node Version Manager for windows, but it's doing an excellent impersonation.
`windows` should be `Windows`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +### shell configuration
Please capitalize `shell` to be `Shell`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +- `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`. This autorizes signed scrips (such as grunt) to run.
Please use `*` for unordered lists.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +- `choco install gsudo`. This will download and install a sudo command line option, that allows shell scripts to ask for elevation on windows (i.e. `sudo` for windows).
`windows` should be `Windows`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +- `choco install yarn`. Yarn ties our javascript code together.
`javascript` should be `JavaScript`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +- `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`. This autorizes signed scrips (such as grunt) to run.
Typo in the word `scrips`. Should be `scripts`.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +Before you start contributing to the Yoast plugins, ensure you've checked out our [development tools page](tools.md) which lists the various tools that need to be used (unless otherwise noted).
This link seems incorrect as it doesn't point to the Windows tools' page.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup.md
> +WP_PLUGIN_DIR=C:\Users\<your name>\Documents\Development\plugin-development-docker\plugins
These changes are for Windows, it seems? Please move it to the dedicated doc for Windows and revert these changes here.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +After installation, GitExtensions will alert you of any missing configurations and you'll need to configure any missing fields. One of the first steps would be to download [Git](https://git-scm.com/d
I believe the part on installing Git should be mentioned _before_ installing GitExtensions as a GUI is optional, whereas Git is not.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +[Add a global git ignore file](/development/standards/version-control-conventions.md#global-git-ignore) so you don't accidentally add system files to the repository.
These sections should probably be moved to the Git section _before_ installing GitExtensions.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +[MySql Workbench](https://dev.mysql.com/downloads/workbench/) is an easy way to access the WordPress databases. Registration is not required, just click `Download` > `No thanks, just start my downloa
This section feels like a duplicate of what is already on the tools page.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +## Set up PHPUnit
Not sure why this header was changed to PHPUnit?

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +*   Behind the checkbox, enter the full path to the `phpunit.xml.dist` file. This file is located in the plugin directory. If the repository contains a `phpunit.xml` file, use that one instead. (i.e
`WordPress-seo` shouldn't have been changed in terms of casing, as it's the repository name.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +* `WP_DEVELOP_DIR` - Refers to the cloned repository of `WordPress-develop`, as it's located on your system.
`WordPress-seo` shouldn't have been changed in terms of casing, as it's the repository name.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +WP_DEVELOP_DIR=C:\Users\<your name>\Documents\Yoast\WordPress-develop\
`WordPress-seo` shouldn't have been changed in terms of casing, as it's the repository name.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +---
This line shouldn't have been moved.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +*   [https://github.com/Yoast/WordPress-seo](https://github.com/Yoast/WordPress-seo)
`WordPress-seo` shouldn't have been changed in terms of casing, as it's the repository name.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +*   [https://WordPress.org/plugins/yoast-test-helper/](https://WordPress.org/plugins/yoast-test-helper/) - Makes testing Yoast SEO, Yoast SEO add-ons and integrations and resetting the different feat
`WordPress-seo` shouldn't have been changed in terms of casing, as it's a link.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +*   [https://github.com/Yoast/yoastseo-amp](https://github.com/Yoast/yoastseo-amp) - Provide additional functionality for The [AMP plugin](https://nl.WordPress.org/plugins/amp/)
`WordPress-seo` shouldn't have been changed in terms of casing, as it's a link.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +* Navigate to your WordPress development environment and are in the correct plugin's directory (i.e. `/plugins/WordPress-seo` or `/plugins/WordPress-seo-premium`).
`WordPress-seo` shouldn't have been changed in terms of casing, as it's the directory name.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +If you're planning on only working on the JavaScript code, outside of a WordPress environment, you can follow the instructions in the [readme](https://github.com/Yoast/JavaScript) of the monorepo, wh
`javascript` shouldn't have been changed in terms of casing, as it's the repository name.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +A list if [useful commands](https://github.com/Yoast/JavaScript#useful-commands) are also available.
`javascript` shouldn't have been changed in terms of casing, as it's a link.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/setup-windows.md
> +After you've cloned the repositories, you can navigate to `basic.WordPress.test` in your browser to see the development environment. Open the plugin directory in your IDE and you should be ready to d
`WordPress` shouldn't have been changed in terms of casing, as it's an URL.

2020-11-27 12:48 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +We recommend following [Jeff Geerling's excellent guide on installing and configuring PHP on windows](https://www.jeffgeerling.com/blog/2018/installing-php-7-and-composer-on-windows-10)
`windows` should be `Windows`.

2020-11-27 12:50 UTC, jcomack commented on docs/development/environment/tools-windows.md
> +- `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`. This autorizes signed scripts (such as `grunt`) to run.
This list style should be changed to use the `*` format.

2022-09-14 10:29 UTC, closed without merging